### ISSUE TITLE
Support for new format of discord webhooks

### ISSUE THREAD

**Issue by Kwandes** [IanMitchell/sentrydiscord.dev#11]
## Goal

Support all available discord webhook formats

### Context

It seems like your code does not account for webhooks created via the discord app
When I create a webhook, its URL does not match the rules defined in the API:

 https://github.com/IanMitchell/sentrydiscord.dev/blob/471192d217878866b1fcbe358ef994546eac6b20/pages/api/create.js#L9-L12
 
The webhook created via the discordApp:
`https://discordapp.com/api/webhooks/1234/A1B2C3`
I was able to modify the above URL to `https://discord.com/api/webhooks/1234/A1B2C3` which your form has accepted, and I've been able to retrieve events from Sentry

### Extra info
Discord app information: 
  - Release Channel: stable,
  - Build Number: 101451

**Comment by IanMitchell** [comment]
Pretty sure discordapp.com is the old way; we've moved our domain over since then
