### ISSUE TITLE
If there is no exception key in payload it returns 500 "key is not defined"

### ISSUE THREAD

**Issue by madmax** [IanMitchell/sentrydiscord.dev#14]
Sentry allow logging error messages without exceptions.
For example:

```
Sentry.captureMessage("Something went wrong");
```
Webhook data will not include event.exception key and sentrydiscord.dev will return 500.

**Comment by IanMitchell** [comment]
Well that's not good lol. Do you happen to have an example payload Sentry sends for that message?
