### ISSUE TITLE
Closing an issue in Sentry generates Discord message

### ISSUE THREAD

**Issue by jcsrb** [IanMitchell/sentrydiscord.dev#18]
<img width="347" alt="Screenshot 2022-02-17 at 10 49 50" src="https://user-images.githubusercontent.com/119011/154439269-22186cfb-cc18-4498-8e47-2209cdeedd16.png">

I am using the hosted version (thanks for running that) and I noticed this change in the last couple of weeks
I am unsure if I misconfigured something or sentry started calling the webhooks in new situations
is this a known situation?

**Comment by IanMitchell** [comment]
Wasn't able to ever figure this one out; closing the issue out but let me know if it's still an issue on your end!
