### ISSUE TITLE
Not sending any alert on event

### ISSUE THREAD

**Issue by AzpektDev** [IanMitchell/sentrydiscord.dev#19]
When there is an error, webhook does not send anything. Let me mention that the "Test plugin" is working and sending a test message. How I can fix it?

**Comment by IanMitchell** [comment]
Hey! Just making sure you got this figured out?

**Comment by AzpektDev** [comment]
Yes, yes.

**Comment by MatheusGalhani** [comment]
I have the same problem he had. But I can't make the problem submissions work, only when I click "test plugin"

**Comment by HerrTxbias** [comment]
@MatheusGalhani Did you add "Send a notification (for all legacy integrations)" in your Alert Rule as an Action?

**Comment by MatheusGalhani** [comment]
@HerrTxbias yes. I open a new issue #24
