### ISSUE TITLE
The issue URL is not added to the message when Sentry is self-hosted

### ISSUE THREAD

**Issue by ProGM** [IanMitchell/sentrydiscord.dev#21]
I've noticed that, in my discord server, the message does not embeds the URL of the issue.

I initially thought it was a missing feature; However, inspecting the sources, I've noticed this lines in message.js:

```javascript
  const link = parser.getLink(event);
  if (
    link.startsWith('https://sentry.io') ||
    link.startsWith('http://sentry.io')
  ) {
    embed.setURL(parser.getLink(event));
  }
```
Check here: https://github.com/IanMitchell/sentrydiscord.dev/blob/main/lib/message.js#L32

Why is this clause there?

Is there some security reason?

If it's ok to remove this if statement, I can make a PR.

**Comment by IanMitchell** [comment]
Hey! I added that because in some instances I was getting relative URLs, which Discord's API rejects. I'll update this to drop the `sentry.io` bit, thanks for the report!
