### ISSUE TITLE
Question: Why we cannot disable analytics and why do you store anything in the DB?

### ISSUE THREAD

**Issue by woss** [IanMitchell/sentrydiscord.dev#26]
Hi,

I wanted to make a PR that would include the docker image file and docker-compose for a faster startup, but I got discouraged by the fact that you are using analytics which i cannot disable. 

Why is that? why cannot we opt-in to use it, one ENV var would be enough to accomplish this with correct code.

Why do you store anything, why not just pass-through?

**Comment by IanMitchell** [comment]
Hey! I host this service on Vercel which doesn't support Docker images. I store simple language analytics in the database to try and make better embeds (the payload is structured differently across languages and frameworks).
