### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by seriaati** [IanMitchell/sentrydiscord.dev#31]
I followed the steps and clicking the "test plugin" button in sentry WebHooks settings does send a message in the channel, but actual issues that occur in the projects don't get send to the channel through discord webhook, so I'm a bit confused.

**Comment by IanMitchell** [comment]
Hey! Sorry for the late response, was out on vacation. Hm this could be two things - either your project isn't sending them, or the application doesn't know how to parse them. Generally I find projects aren't configured to send notifications. Double check your notification settings are set to notify webhooks when new issues are discovered. A more in-depth guide on that is available in my Discord: [https://discord.gg/ian](https://discord.gg/ian) (I should really work on putting this on the site lol)

**Comment by wittjosiah** [comment]
I had the same issue and needed to add legacy integrations to the alert notification rules to fix it
![image](https://user-images.githubusercontent.com/4529818/224081988-c3aab5d1-31b0-4c13-9fb5-6a0df6dac468.png)
