### ISSUE TITLE
Project name in Notification

### ISSUE THREAD

**Issue by RodionBezruk** [IanMitchell/sentrydiscord.dev#32]
Hey 

If you have multiple projects in Sentry, will be very useful if possible to get info about which project gets the error inside the discord notification. Any ideas? Thanks

**Comment by RodionBezruk** [comment]
After some debugging of the code, I found the issue. 
https://github.com/IanMitchell/sentrydiscord.dev/blob/03e354d15ce095b2ed4e609ca9150a47bc8fa2e7/lib/parser.ts
Line:7 

Seems we need to replace one line of the code:
return getEvent(issue)?.project?.name;
--->>>
return issue?.project?.project_name;

https://tppr.me/gVP1h

Right now we are using versions of Sentry 21.8.0.dev0
The latest is 23.4.0. Maybe the webhook object's response is changed in the latest version of Sentry. We will try to update the Sentry. Hope it will solve the issue ;) I will back with the result.

**Comment by IanMitchell** [comment]
Thanks for the reply and the debugging! Just pushed a change, should be out shortly - if this doesn't actually solve your issue, let me know and we can take another look! 😄
