### ISSUE TITLE
I am not getting the issues on my discord channel

### ISSUE THREAD

**Issue by pokharelanchit** [IanMitchell/sentrydiscord.dev#39]
Test works. It sends an example sentry message to my discord channel. But issues are not sent.

**Comment by mlnrDev** [comment]
make sure you create an alert in the Alerts tab, like so:

<details>
<summary>Screenshot</summary>

![](https://i.imgur.com/dqVLOt3.png)
</details>

**Comment by punkpeye** [comment]
These instructions should be added to https://sentrydiscord.dev/create

**Comment by IanMitchell** [comment]
If you want to PR them, I can merge it in!
