### ISSUE TITLE
Changes on discord's domain

### ISSUE THREAD

**Issue by VitorSponhardi** [IanMitchell/sentrydiscord.dev#40]
Hi !
I'm trying to create a link and actually the discord changed the domain on hook urls, now they are using "discordapp.com".
On the site, when i put this new link, returns to me a error "Please use a Discord webhook URL!".

By the way, thank you so much for this project, so far i have only been able to send alerts to my discord thanks to you!

**Comment by IanMitchell** [comment]
Hey! `discordapp.com` is the old URL scheme - you should be using `discord.com` now instead. You should be able to just change the root domain to the new style, the rest of the URL will be the same!

For more information, you can see [@colinloretz's message here](https://discord.com/channels/613425648685547541/697138785317814292/1163963748583735338) in the [Discord Developers server](https://discord.gg/discord-developers)

**Comment by IanMitchell** [comment]
Web accessible link: https://github.com/discord/discord-api-docs/discussions/6490 (thanks Colin!)
