### ISSUE TITLE
"Unable to generate code snippet" error

### ISSUE THREAD

**Issue by 1-Rasky-1** [IanMitchell/sentrydiscord.dev#43]
I created a Custom Integration in Sentry and configured it as shown in the image below.
However, an error message "Unable to generate code snippet." is sent to discord.

![image](https://github.com/IanMitchell/sentrydiscord.dev/assets/108844047/79e7bd25-11a3-4d8f-8f44-eba29cf5db89)
![image](https://github.com/IanMitchell/sentrydiscord.dev/assets/108844047/5ae9257e-4fbc-4dd2-9bbc-ee960a885d52)
![image](https://github.com/IanMitchell/sentrydiscord.dev/assets/108844047/3b6e0c32-467a-48d2-a9be-518fa6781d9d)

**Comment by IanMitchell** [comment]
Hey! Generally this is because the webhook payload differs a little bit than how I'm parsing - they're untyped which means I'll need an example payload to fix it though :(. If you can post one here I'll gladly add support!
